### --------
### TESTING 
### --------

### get all users
http://localhost:3000/users

### -----
### AUTH 
### -----

### signin
# @name login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "lorem@ipsum.test",
  "password": "Test1234"
}

### ---------
### SETTINGS 
### ---------

@authToken = {{login.response.body.token}}